### ISSUE TITLE
自动化 Actions 使用的详细流程

### ISSUE THREAD

**Issue by NanFangZhe404** [kagurazakayashi/CodeNotebook#3]
你好，想问一下，这个项目是怎么个自动化流程呢？ Actions 是如何利用起来，是在自己的服务器然后有脚本每天指定时间去执行这个 main.yml 文件吗？: )

**Comment by kagurazakayashi** [comment]
不需要服务器去触发的，你可以参考 [.github/workflows/main.yml](https://github.com/kagurazakayashi/CodeNotebook/blob/master/.github/workflows/main.yml) ，里面做了注释。
`on:` 控制了它会在什么时候执行，此处定义了 `push: branches: [ master ]` ，也就是说当我向 master 分支提交改变时， Github 就会自动运行它 `jobs` 中定义的内容。
当然也可以不由 Actions 执行而是由服务器来进行这些操作。至于时间看起来不匹配是我故意整活的（
